version: "3.9"
services:
  tf:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./tf:/tf
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  